# OperatorGroup resource for RHSSO
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rhsso-test
  namespace: rhsso-test
spec:
  targetNamespaces:
  - rhsso-test
