apiVersion: v1 
kind: Secret 
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: keycloak-db-secret 
  namespace: rhsso-prod
  stringData: 
    POSTGRES_DATABASE: pgsql-admin
    POSTGRES_EXTERNAL_ADDRESS: pgsql-password
    POSTGRES_EXTERNAL_PORT: postgresql.pgsql-prod.svc.cluster.local:5432