apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso-dev
  labels:
    app: sso
  namespace: rh-sso-dev
spec:
  multiAvailablityZones:
    enabled: true
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: Always
  postgresDeploymentSpec:
    imagePullPolicy: Always
  instances: 2
  storageClassName: gp2


classic load balancer 

application/network load balancer